#!/usr/bin/env python
# -*- coding: utf8 -*-

from necrolib import webget
from necrolib import utils
import sys
from necrolib import ConfigObj
from necrolib import datadir

cfg_file = datadir.user_data_dir("necroposter/uploader.cfg")
config = ConfigObj(cfg_file)

def check_config():
        try:
            u = config['fo_user']
            p = config['fo_pass']
            if u == '' or p == '':
                print "empty cfg"
                u, p = setup_cfg()
        except KeyError:
            u, p = setup_cfg()
        return u, p

def setup_cfg():
        print "Starting configuration"
        u = raw_input('Please enter FilEx username-> ')
        p = raw_input('Please enter FilEx password-> ')
        config['fo_user'] = u
        config['fo_pass'] = p
        config.write()
        return u, p

def upl_file(n, u, p):
        wg = webget()
        wg.init_cookie(u, p)
        print n[0]
        k = wg.upload_file(n[0])
        #print utils.getnum(utils.get_urls_meta(k[2]))
        print k



def main(n):
        if len(n) == 0:
                print "Pass filename as argument"
                sys.exit(1)
        else:
                u, p = check_config()
                upl_file(n, u, p)


if __name__ == "__main__":
    main(sys.argv[1:])

