# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created: Sat Sep  6 15:05:31 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748,741)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/icon.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tabWidget_2 = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0,150))
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabImages = QtGui.QWidget()
        self.tabImages.setObjectName("tabImages")
        self.gridlayout = QtGui.QGridLayout(self.tabImages)
        self.gridlayout.setObjectName("gridlayout")
        self.frame = QtGui.QFrame(self.tabImages)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.hboxlayout = QtGui.QHBoxLayout(self.frame)
        self.hboxlayout.setObjectName("hboxlayout")
        self.imgList = QtGui.QListWidget(self.frame)
        self.imgList.setIconSize(QtCore.QSize(150,150))
        self.imgList.setObjectName("imgList")
        self.hboxlayout.addWidget(self.imgList)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.btnAdd = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/add.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon)
        self.btnAdd.setObjectName("btnAdd")
        self.vboxlayout1.addWidget(self.btnAdd)
        self.btnAddFolder = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/add-folder.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.btnAddFolder.setIcon(icon)
        self.btnAddFolder.setObjectName("btnAddFolder")
        self.vboxlayout1.addWidget(self.btnAddFolder)
        self.btnRemove = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/delete.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon)
        self.btnRemove.setObjectName("btnRemove")
        self.vboxlayout1.addWidget(self.btnRemove)
        self.btnDelete = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/trash.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon)
        self.btnDelete.setObjectName("btnDelete")
        self.vboxlayout1.addWidget(self.btnDelete)
        self.btnCoverFlow = QtGui.QPushButton(self.frame)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/coverflow.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.btnCoverFlow.setIcon(icon)
        self.btnCoverFlow.setCheckable(True)
        self.btnCoverFlow.setObjectName("btnCoverFlow")
        self.vboxlayout1.addWidget(self.btnCoverFlow)
        spacerItem = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout1.addItem(spacerItem)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.gridlayout.addWidget(self.frame,0,0,1,1)
        self.tabWidget_2.addTab(self.tabImages,"")
        self.tabWatermark = QtGui.QWidget()
        self.tabWatermark.setObjectName("tabWatermark")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.tabWatermark)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.frame_5 = QtGui.QGroupBox(self.tabWatermark)
        self.frame_5.setCheckable(False)
        self.frame_5.setObjectName("frame_5")
        self.gridlayout1 = QtGui.QGridLayout(self.frame_5)
        self.gridlayout1.setObjectName("gridlayout1")
        self.rbUpperLeft = QtGui.QRadioButton(self.frame_5)
        self.rbUpperLeft.setChecked(True)
        self.rbUpperLeft.setObjectName("rbUpperLeft")
        self.gridlayout1.addWidget(self.rbUpperLeft,0,0,1,1)
        self.rbUpperRight = QtGui.QRadioButton(self.frame_5)
        self.rbUpperRight.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rbUpperRight.setObjectName("rbUpperRight")
        self.gridlayout1.addWidget(self.rbUpperRight,0,2,1,1)
        self.rbBottomLeft = QtGui.QRadioButton(self.frame_5)
        self.rbBottomLeft.setObjectName("rbBottomLeft")
        self.gridlayout1.addWidget(self.rbBottomLeft,2,0,1,1)
        self.rbBottomRight = QtGui.QRadioButton(self.frame_5)
        self.rbBottomRight.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rbBottomRight.setObjectName("rbBottomRight")
        self.gridlayout1.addWidget(self.rbBottomRight,2,2,1,1)
        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1,1,0,1,1)
        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem2,0,1,1,1)
        self.rbScaled = QtGui.QRadioButton(self.frame_5)
        self.rbScaled.setObjectName("rbScaled")
        self.gridlayout1.addWidget(self.rbScaled,4,0,1,1)
        self.rbTiled = QtGui.QRadioButton(self.frame_5)
        self.rbTiled.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.rbTiled.setObjectName("rbTiled")
        self.gridlayout1.addWidget(self.rbTiled,4,2,1,1)
        spacerItem3 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem3,3,0,1,1)
        self.rbCustom = QtGui.QRadioButton(self.frame_5)
        self.rbCustom.setObjectName("rbCustom")
        self.gridlayout1.addWidget(self.rbCustom,6,0,1,1)
        spacerItem4 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem4,6,1,1,2)
        spacerItem5 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem5,5,1,1,1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.labelX = QtGui.QLabel(self.frame_5)
        self.labelX.setEnabled(False)
        self.labelX.setObjectName("labelX")
        self.hboxlayout2.addWidget(self.labelX)
        self.watermarkX = QtGui.QLineEdit(self.frame_5)
        self.watermarkX.setEnabled(False)
        self.watermarkX.setObjectName("watermarkX")
        self.hboxlayout2.addWidget(self.watermarkX)
        self.labelY = QtGui.QLabel(self.frame_5)
        self.labelY.setEnabled(False)
        self.labelY.setObjectName("labelY")
        self.hboxlayout2.addWidget(self.labelY)
        self.watermarkY = QtGui.QLineEdit(self.frame_5)
        self.watermarkY.setEnabled(False)
        self.watermarkY.setObjectName("watermarkY")
        self.hboxlayout2.addWidget(self.watermarkY)
        self.gridlayout1.addLayout(self.hboxlayout2,7,0,1,3)
        self.vboxlayout2.addWidget(self.frame_5)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label = QtGui.QLabel(self.tabWatermark)
        self.label.setObjectName("label")
        self.hboxlayout3.addWidget(self.label)
        self.spinOpacity = QtGui.QDoubleSpinBox(self.tabWatermark)
        self.spinOpacity.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spinOpacity.setMaximum(1.0)
        self.spinOpacity.setSingleStep(0.1)
        self.spinOpacity.setProperty("value",QtCore.QVariant(1.0))
        self.spinOpacity.setObjectName("spinOpacity")
        self.hboxlayout3.addWidget(self.spinOpacity)
        self.vboxlayout2.addLayout(self.hboxlayout3)
        self.hboxlayout1.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.pbAddWatermark = QtGui.QPushButton(self.tabWatermark)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/add.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.pbAddWatermark.setIcon(icon)
        self.pbAddWatermark.setObjectName("pbAddWatermark")
        self.vboxlayout3.addWidget(self.pbAddWatermark)
        self.pbRemoveWatermark = QtGui.QPushButton(self.tabWatermark)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/delete.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.pbRemoveWatermark.setIcon(icon)
        self.pbRemoveWatermark.setObjectName("pbRemoveWatermark")
        self.vboxlayout3.addWidget(self.pbRemoveWatermark)
        self.groupBox = QtGui.QGroupBox(self.tabWatermark)
        self.groupBox.setObjectName("groupBox")
        self.hboxlayout4 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.displayWatermark = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayWatermark.sizePolicy().hasHeightForWidth())
        self.displayWatermark.setSizePolicy(sizePolicy)
        self.displayWatermark.setObjectName("displayWatermark")
        self.hboxlayout4.addWidget(self.displayWatermark)
        self.vboxlayout3.addWidget(self.groupBox)
        self.hboxlayout1.addLayout(self.vboxlayout3)
        self.tabWidget_2.addTab(self.tabWatermark,"")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10,10,391,71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5,1,1,1,1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6,0,1,1,1)
        self.le_p = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_p.setFrame(True)
        self.le_p.setEchoMode(QtGui.QLineEdit.Password)
        self.le_p.setObjectName("le_p")
        self.gridLayout.addWidget(self.le_p,1,2,1,1)
        self.le_u = QtGui.QLineEdit(self.gridLayoutWidget)
        self.le_u.setObjectName("le_u")
        self.gridLayout.addWidget(self.le_u,0,2,1,1)
        self.pb_saveset = QtGui.QPushButton(self.tab_2)
        self.pb_saveset.setGeometry(QtCore.QRect(240,100,75,24))
        self.pb_saveset.setObjectName("pb_saveset")
        self.tabWidget_2.addTab(self.tab_2,"")
        self.vboxlayout.addWidget(self.tabWidget_2)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.hboxlayout5 = QtGui.QHBoxLayout(self.tab)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.textBBCode = QtGui.QTextEdit(self.tab)
        self.textBBCode.setObjectName("textBBCode")
        self.hboxlayout5.addWidget(self.textBBCode)
        self.tabWidget.addTab(self.tab,"")
        self.vboxlayout.addWidget(self.tabWidget)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.hboxlayout6.addWidget(self.label_2)
        self.spinImg = QtGui.QSpinBox(self.centralwidget)
        self.spinImg.setMinimum(1)
        self.spinImg.setProperty("value",QtCore.QVariant(4))
        self.spinImg.setObjectName("spinImg")
        self.hboxlayout6.addWidget(self.spinImg)
        spacerItem6 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem6)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.hboxlayout6.addWidget(self.label_3)
        self.comboFormat = QtGui.QComboBox(self.centralwidget)
        self.comboFormat.setObjectName("comboFormat")
        self.hboxlayout6.addWidget(self.comboFormat)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.hboxlayout6.addWidget(self.label_4)
        self.spinQuality = QtGui.QSpinBox(self.centralwidget)
        self.spinQuality.setEnabled(False)
        self.spinQuality.setMaximum(100)
        self.spinQuality.setObjectName("spinQuality")
        self.hboxlayout6.addWidget(self.spinQuality)
        self.vboxlayout.addLayout(self.hboxlayout6)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.comboSite = QtGui.QComboBox(self.centralwidget)
        self.comboSite.setObjectName("comboSite")
        self.hboxlayout7.addWidget(self.comboSite)
        self.btnUpload = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/upload.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.btnUpload.setIcon(icon)
        self.btnUpload.setObjectName("btnUpload")
        self.hboxlayout7.addWidget(self.btnUpload)
        self.btnCancel = QtGui.QPushButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new/prefix1/img/cancel.png"),QtGui.QIcon.Normal,QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon)
        self.btnCancel.setObjectName("btnCancel")
        self.hboxlayout7.addWidget(self.btnCancel)
        self.vboxlayout.addLayout(self.hboxlayout7)
        self.lblTotal = QtGui.QLabel(self.centralwidget)
        self.lblTotal.setObjectName("lblTotal")
        self.vboxlayout.addWidget(self.lblTotal)
        self.pbTotal = QtGui.QProgressBar(self.centralwidget)
        self.pbTotal.setProperty("value",QtCore.QVariant(0))
        self.pbTotal.setObjectName("pbTotal")
        self.vboxlayout.addWidget(self.pbTotal)
        self.lblPartial = QtGui.QLabel(self.centralwidget)
        self.lblPartial.setObjectName("lblPartial")
        self.vboxlayout.addWidget(self.lblPartial)
        self.pbPartial = QtGui.QProgressBar(self.centralwidget)
        self.pbPartial.setProperty("value",QtCore.QVariant(0))
        self.pbPartial.setObjectName("pbPartial")
        self.vboxlayout.addWidget(self.pbPartial)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,748,26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Image Uploader", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddFolder.setText(QtGui.QApplication.translate("MainWindow", "Add Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRemove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete Images", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCoverFlow.setText(QtGui.QApplication.translate("MainWindow", "CoverFlow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabImages), QtGui.QApplication.translate("MainWindow", "Images", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_5.setTitle(QtGui.QApplication.translate("MainWindow", "Position", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUpperLeft.setText(QtGui.QApplication.translate("MainWindow", "UpperLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.rbUpperRight.setText(QtGui.QApplication.translate("MainWindow", "UpperRight", None, QtGui.QApplication.UnicodeUTF8))
        self.rbBottomLeft.setText(QtGui.QApplication.translate("MainWindow", "BottomLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.rbBottomRight.setText(QtGui.QApplication.translate("MainWindow", "BottomRight", None, QtGui.QApplication.UnicodeUTF8))
        self.rbScaled.setText(QtGui.QApplication.translate("MainWindow", "Scaled", None, QtGui.QApplication.UnicodeUTF8))
        self.rbTiled.setText(QtGui.QApplication.translate("MainWindow", "Tiled", None, QtGui.QApplication.UnicodeUTF8))
        self.rbCustom.setText(QtGui.QApplication.translate("MainWindow", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX.setText(QtGui.QApplication.translate("MainWindow", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY.setText(QtGui.QApplication.translate("MainWindow", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Watermark opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.pbAddWatermark.setText(QtGui.QApplication.translate("MainWindow", "Add Watermark", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRemoveWatermark.setText(QtGui.QApplication.translate("MainWindow", "Remove Watermark", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWatermark), QtGui.QApplication.translate("MainWindow", "Watermark", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "FileEx password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "FileEx username", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_saveset.setText(QtGui.QApplication.translate("MainWindow", "Save settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "FileEx Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "BBCode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Images per line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Image format", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFormat.addItem(QtGui.QApplication.translate("MainWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFormat.addItem(QtGui.QApplication.translate("MainWindow", "PNG", None, QtGui.QApplication.UnicodeUTF8))
        self.comboFormat.addItem(QtGui.QApplication.translate("MainWindow", "JPEG", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Quality", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpload.setText(QtGui.QApplication.translate("MainWindow", "Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
